# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'Default'

variables:
  - group: 'testgroup'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzurePowerShell@5
  env:
    $triggerList : $(triggerlist)
  inputs:
    azureSubscription: 'ARM-WIF-Automatic-APK'
    ScriptType: 'InlineScript'
    Inline: |
      $triggerNames = @("Trigger 1")
      # Retrieve all triggers from the specified Synapse workspace
      $triggersSynapse = Get-AzSynapseTrigger -WorkspaceName "apk"
      # Loop through the list of trigger names and start each one
      $triggerNames | ForEach-Object {
          $triggerName = $_  # The current trigger name in the loop
          $trigger = $triggersSynapse | Where-Object { $_.Name -eq $triggerName }
          if ($trigger) {
              Stop-AzSynapseTrigger -WorkspaceName "apk"  -Name $trigger.Name
              Write-Host "Started trigger: $($trigger.Name)"
          } else {
              Write-Host "Trigger '$($_)' not found in the workspace."
          }
      }
    preferredAzurePowerShellVersion: '9.4.0'
  displayName: 'stop Synapse triggers'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'ARM-WIF-Automatic-APK'
    ScriptType: 'InlineScript'
    Inline: |
      $triggerNames = @("Trigger 1")
            # Retrieve all triggers from the specified Synapse workspace
            $triggersSynapse = Get-AzSynapseTrigger -WorkspaceName "apk"
            # Loop through the list of trigger names and start each one
            $triggerNames | ForEach-Object {
                $triggerName = $_  # The current trigger name in the loop
                $trigger = $triggersSynapse | Where-Object { $_.Name -eq $triggerName }
                if ($trigger) {
                    Start-AzSynapseTrigger -WorkspaceName "apk"  -Name $trigger.Name
                    Write-Host "Started trigger: $($trigger.Name)"
                } else {
                    Write-Host "Trigger '$($_)' not found in the workspace."
                }
            }
    azurePowerShellVersion: 'LatestVersion'
  displayName: 'start Synapse triggers'
